<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActividadEconomicaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $actividades = [
            ['codigo' => '1111', 'valor' => 'Cultivo de cereales excepto arroz y para forrajes', 'status' => 'Desactivado'],
            ['codigo' => '1112', 'valor' => 'Cultivo de legumbres', 'status' => 'Desactivado'],
            ['codigo' => '1113', 'valor' => 'Cultivo de semillas oleaginosas', 'status' => 'Desactivado'],
            ['codigo' => '1114', 'valor' => 'Cultivo de plantas para la preparación de semillas', 'status' => 'Desactivado'],
            ['codigo' => '1119', 'valor' => 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '1120', 'valor' => 'Cultivo de arroz', 'status' => 'Desactivado'],
            ['codigo' => '1131', 'valor' => 'Cultivo de raíces y tubérculos', 'status' => 'Desactivado'],
            ['codigo' => '1132', 'valor' => 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares', 'status' => 'Desactivado'],
            ['codigo' => '1133', 'valor' => 'Cultivo hortícola de fruto', 'status' => 'Desactivado'],
            ['codigo' => '1134', 'valor' => 'Cultivo de hortalizas de hoja y otras hortalizas ncp', 'status' => 'Desactivado'],
            ['codigo' => '1140', 'valor' => 'Cultivo de caña de azúcar', 'status' => 'Desactivado'],
            ['codigo' => '1150', 'valor' => 'Cultivo de tabaco', 'status' => 'Desactivado'],
            ['codigo' => '1161', 'valor' => 'Cultivo de algodón', 'status' => 'Desactivado'],
            ['codigo' => '1162', 'valor' => 'Cultivo de fibras vegetales excepto algodón', 'status' => 'Desactivado'],
            ['codigo' => '1191', 'valor' => 'Cultivo de plantas no perennes para la producción de semillas y flores', 'status' => 'Desactivado'],
            ['codigo' => '1192', 'valor' => 'Cultivo de cereales y pastos para la alimentación animal', 'status' => 'Desactivado'],
            ['codigo' => '1199', 'valor' => 'Producción de cultivos no estacionales ncp', 'status' => 'Desactivado'],
            ['codigo' => '1220', 'valor' => 'Cultivo de frutas tropicales', 'status' => 'Desactivado'],
            ['codigo' => '1230', 'valor' => 'Cultivo de cítricos', 'status' => 'Desactivado'],
            ['codigo' => '1240', 'valor' => 'Cultivo de frutas de pepita y hueso', 'status' => 'Desactivado'],
            ['codigo' => '1251', 'valor' => 'Cultivo de frutas ncp', 'status' => 'Desactivado'],
            ['codigo' => '1252', 'valor' => 'Cultivo de otros frutos y nueces de árboles y arbustos', 'status' => 'Desactivado'],
            ['codigo' => '1260', 'valor' => 'Cultivo de frutos oleaginosos', 'status' => 'Desactivado'],
            ['codigo' => '1271', 'valor' => 'Cultivo de café', 'status' => 'Desactivado'],
            ['codigo' => '1272', 'valor' => 'Cultivo de plantas para la elaboración de bebidas excepto café', 'status' => 'Desactivado'],
            ['codigo' => '1281', 'valor' => 'Cultivo de especias y aromáticas', 'status' => 'Desactivado'],
            ['codigo' => '1282', 'valor' => 'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos', 'status' => 'Desactivado'],
            ['codigo' => '1291', 'valor' => 'Cultivo de árboles de hule (caucho) para la obtención de látex', 'status' => 'Desactivado'],
            ['codigo' => '1292', 'valor' => 'Cultivo de plantas para la obtención de productos químicos y colorantes', 'status' => 'Desactivado'],
            ['codigo' => '1299', 'valor' => 'Producción de cultivos perennes ncp', 'status' => 'Desactivado'],
            ['codigo' => '1300', 'valor' => 'Propagación de plantas', 'status' => 'Desactivado'],
            ['codigo' => '1301', 'valor' => 'Cultivo de plantas y flores ornamentales', 'status' => 'Desactivado'],
            ['codigo' => '1410', 'valor' => 'Cría y engorde de ganado bovino', 'status' => 'Desactivado'],
            ['codigo' => '1420', 'valor' => 'Cría de caballos y otros equinos', 'status' => 'Desactivado'],
            ['codigo' => '1440', 'valor' => 'Cría de ovejas y cabras', 'status' => 'Desactivado'],
            ['codigo' => '1450', 'valor' => 'Cría de cerdos', 'status' => 'Desactivado'],
            ['codigo' => '1460', 'valor' => 'Cría de aves de corral y producción de huevos', 'status' => 'Desactivado'],
            ['codigo' => '1491', 'valor' => 'Cría de abejas apicultura para la obtención de miel y otros productos apícolas', 'status' => 'Desactivado'],
            ['codigo' => '1492', 'valor' => 'Cría de conejos', 'status' => 'Desactivado'],
            ['codigo' => '1493', 'valor' => 'Cría de iguanas y garrobos', 'status' => 'Desactivado'],
            ['codigo' => '1494', 'valor' => 'Cría de mariposas y otros insectos', 'status' => 'Desactivado'],
            ['codigo' => '1499', 'valor' => 'Cría y obtención de productos animales n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '1500', 'valor' => 'Cultivo de productos agrícolas en combinación con la cría de animales', 'status' => 'Desactivado'],
            ['codigo' => '1611', 'valor' => 'Servicios de maquinaria agrícola', 'status' => 'Desactivado'],
            ['codigo' => '1612', 'valor' => 'Control de plagas', 'status' => 'Desactivado'],
            ['codigo' => '1613', 'valor' => 'Servicios de riego', 'status' => 'Desactivado'],
            ['codigo' => '1614', 'valor' => 'Servicios de contratación de mano de obra para la agricultura', 'status' => 'Desactivado'],
            ['codigo' => '1619', 'valor' => 'Servicios agrícolas ncp', 'status' => 'Desactivado'],
            ['codigo' => '1621', 'valor' => 'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos', 'status' => 'Desactivado'],
            ['codigo' => '1622', 'valor' => 'Servicios de mano de obra pecuaria', 'status' => 'Desactivado'],
            ['codigo' => '1629', 'valor' => 'Servicios pecuarios ncp', 'status' => 'Desactivado'],
            ['codigo' => '1631', 'valor' => 'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria', 'status' => 'Desactivado'],
            ['codigo' => '1632', 'valor' => 'Servicio de beneficio de café', 'status' => 'Desactivado'],
            ['codigo' => '1633', 'valor' => 'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)', 'status' => 'Desactivado'],
            ['codigo' => '1640', 'valor' => 'Tratamiento de semillas para la propagación', 'status' => 'Desactivado'],
            ['codigo' => '1700', 'valor' => 'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos', 'status' => 'Desactivado'],
            ['codigo' => '2100', 'valor' => 'Silvicultura y otras actividades forestales', 'status' => 'Desactivado'],
            ['codigo' => '2200', 'valor' => 'Extracción de madera', 'status' => 'Desactivado'],
            ['codigo' => '2300', 'valor' => 'Recolección de productos diferentes a la madera', 'status' => 'Desactivado'],
            ['codigo' => '2400', 'valor' => 'Servicios de apoyo a la silvicultura', 'status' => 'Desactivado'],
            ['codigo' => '3110', 'valor' => 'Pesca marítima de altura y costera', 'status' => 'Desactivado'],
            ['codigo' => '3120', 'valor' => 'Pesca de agua dulce', 'status' => 'Desactivado'],
            ['codigo' => '3210', 'valor' => 'Acuicultura marítima', 'status' => 'Desactivado'],
            ['codigo' => '3220', 'valor' => 'Acuicultura de agua dulce', 'status' => 'Desactivado'],
            ['codigo' => '3300', 'valor' => 'Servicios de apoyo a la pesca y acuicultura', 'status' => 'Desactivado'],
            ['codigo' => '5100', 'valor' => 'Extracción de hulla', 'status' => 'Desactivado'],
            ['codigo' => '5200', 'valor' => 'Extracción y aglomeración de lignito', 'status' => 'Desactivado'],
            ['codigo' => '6100', 'valor' => 'Extracción de petróleo crudo', 'status' => 'Desactivado'],
            ['codigo' => '6200', 'valor' => 'Extracción de gas natural', 'status' => 'Desactivado'],
            ['codigo' => '7100', 'valor' => 'Extracción de minerales de hierro', 'status' => 'Desactivado'],
            ['codigo' => '7210', 'valor' => 'Extracción de minerales de uranio y torio', 'status' => 'Desactivado'],
            ['codigo' => '7290', 'valor' => 'Extracción de minerales metalíferos no ferrosos', 'status' => 'Desactivado'],
            ['codigo' => '8100', 'valor' => 'Extracción de piedra, arena y arcilla', 'status' => 'Desactivado'],
            ['codigo' => '8910', 'valor' => 'Extracción de minerales para la fabricación de abonos y productos químicos', 'status' => 'Desactivado'],
            ['codigo' => '8920', 'valor' => 'Extracción y aglomeración de turba', 'status' => 'Desactivado'],
            ['codigo' => '8930', 'valor' => 'Extracción de sal', 'status' => 'Desactivado'],
            ['codigo' => '8990', 'valor' => 'Explotación de otras minas y canteras ncp', 'status' => 'Desactivado'],
            ['codigo' => '9100', 'valor' => 'Actividades de apoyo a la extracción de petróleo y gas natural', 'status' => 'Desactivado'],
            ['codigo' => '9900', 'valor' => 'Actividades de apoyo a la explotación de minas y canteras', 'status' => 'Desactivado'],
            ['codigo' => '10101', 'valor' => 'Servicio de rastros y mataderos de bovinos y porcinos', 'status' => 'Desactivado'],
            ['codigo' => '10102', 'valor' => 'Matanza y procesamiento de bovinos y porcinos', 'status' => 'Desactivado'],
            ['codigo' => '10103', 'valor' => 'Matanza y procesamientos de aves de corral', 'status' => 'Desactivado'],
            ['codigo' => '10104', 'valor' => 'Elaboración y conservación de embutidos y tripas naturales', 'status' => 'Desactivado'],
            ['codigo' => '10105', 'valor' => 'Servicios de conservación y empaque de carnes', 'status' => 'Desactivado'],
            ['codigo' => '10106', 'valor' => 'Elaboración y conservación de grasas y aceites animales', 'status' => 'Desactivado'],
            ['codigo' => '10107', 'valor' => 'Servicios de molienda de carne', 'status' => 'Desactivado'],
            ['codigo' => '10108', 'valor' => 'Elaboración de productos de carne ncp', 'status' => 'Desactivado'],
            ['codigo' => '10201', 'valor' => 'Procesamiento y conservación de pescado, crustáceos y moluscos', 'status' => 'Desactivado'],
            ['codigo' => '10209', 'valor' => 'Fabricación de productos de pescado ncp', 'status' => 'Desactivado'],
            ['codigo' => '10301', 'valor' => 'Elaboración de jugos de frutas y hortalizas', 'status' => 'Desactivado'],
            ['codigo' => '10302', 'valor' => 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas', 'status' => 'Desactivado'],
            ['codigo' => '10309', 'valor' => 'Elaboración de productos de frutas y hortalizas n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '10401', 'valor' => 'Fabricación de aceites y grasas vegetales y animales comestibles', 'status' => 'Desactivado'],
            ['codigo' => '10402', 'valor' => 'Fabricación de aceites y grasas vegetales y animales no comestibles', 'status' => 'Desactivado'],
            ['codigo' => '10409', 'valor' => 'Servicio de maquilado de aceites', 'status' => 'Desactivado'],
            ['codigo' => '10501', 'valor' => 'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos', 'status' => 'Desactivado'],
            ['codigo' => '10502', 'valor' => 'Fabricación de sorbetes y helados', 'status' => 'Desactivado'],
            ['codigo' => '10503', 'valor' => 'Fabricación de quesos', 'status' => 'Desactivado'],
            ['codigo' => '10611', 'valor' => 'Molienda de cereales', 'status' => 'Desactivado'],
            ['codigo' => '10612', 'valor' => 'Elaboración de cereales para el desayuno y similares', 'status' => 'Desactivado'],
            ['codigo' => '10613', 'valor' => 'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163)', 'status' => 'Desactivado'],
            ['codigo' => '10621', 'valor' => 'Fabricación de almidón', 'status' => 'Desactivado'],
            ['codigo' => '10628', 'valor' => 'Servicio de molienda de maíz húmedo molino para nixtamal', 'status' => 'Desactivado'],
            ['codigo' => '10711', 'valor' => 'Elaboración de tortillas', 'status' => 'Desactivado'],
            ['codigo' => '10712', 'valor' => 'Fabricación de pan, galletas y barquillos', 'status' => 'Desactivado'],
            ['codigo' => '10713', 'valor' => 'Fabricación de repostería', 'status' => 'Desactivado'],
            ['codigo' => '10721', 'valor' => 'Ingenios azucareros', 'status' => 'Desactivado'],
            ['codigo' => '10722', 'valor' => 'Molienda de caña de azúcar para la elaboración de dulces', 'status' => 'Desactivado'],
            ['codigo' => '10723', 'valor' => 'Elaboración de jarabes de azúcar y otros similares', 'status' => 'Desactivado'],
            ['codigo' => '10724', 'valor' => 'Maquilado de azúcar de caña', 'status' => 'Desactivado'],
            ['codigo' => '10730', 'valor' => 'Fabricación de cacao, chocolates y productos de confitería', 'status' => 'Desactivado'],
            ['codigo' => '10740', 'valor' => 'Elaboración de macarrones, fideos, y productos farináceos similares', 'status' => 'Desactivado'],
            ['codigo' => '10750', 'valor' => 'Elaboración de comidas y platos preparados para la reventa en locales y/o para exportación', 'status' => 'Desactivado'],
            ['codigo' => '10791', 'valor' => 'Elaboración de productos de café', 'status' => 'Desactivado'],
            ['codigo' => '10792', 'valor' => 'Elaboración de especies, sazonadores y condimentos', 'status' => 'Desactivado'],
            ['codigo' => '10793', 'valor' => 'Elaboración de sopas, cremas y consomé', 'status' => 'Desactivado'],
            ['codigo' => '10794', 'valor' => 'Fabricación de bocadillos tostados y/o fritos', 'status' => 'Desactivado'],
            ['codigo' => '10799', 'valor' => 'Elaboración de productos alimenticios ncp', 'status' => 'Desactivado'],
            ['codigo' => '10800', 'valor' => 'Elaboración de alimentos preparados para animales', 'status' => 'Desactivado'],
            ['codigo' => '11012', 'valor' => 'Fabricación de aguardiente y licores', 'status' => 'Desactivado'],
            ['codigo' => '11020', 'valor' => 'Elaboración de vinos', 'status' => 'Desactivado'],
            ['codigo' => '11030', 'valor' => 'Fabricación de cerveza', 'status' => 'Desactivado'],
            ['codigo' => '11041', 'valor' => 'Fabricación de aguas gaseosas', 'status' => 'Desactivado'],
            ['codigo' => '11042', 'valor' => 'Fabricación y envasado de agua', 'status' => 'Desactivado'],
            ['codigo' => '11043', 'valor' => 'Elaboración de refrescos', 'status' => 'Desactivado'],
            ['codigo' => '11048', 'valor' => 'Maquilado de aguas gaseosas', 'status' => 'Desactivado'],
            ['codigo' => '11049', 'valor' => 'Elaboración de bebidas no alcohólicas', 'status' => 'Desactivado'],
            ['codigo' => '12000', 'valor' => 'Elaboración de productos de tabaco', 'status' => 'Desactivado'],
            ['codigo' => '13111', 'valor' => 'Preparación de fibras textiles', 'status' => 'Desactivado'],
            ['codigo' => '13112', 'valor' => 'Fabricación de hilados', 'status' => 'Desactivado'],
            ['codigo' => '13120', 'valor' => 'Fabricación de telas', 'status' => 'Desactivado'],
            ['codigo' => '13130', 'valor' => 'Acabado de productos textiles', 'status' => 'Desactivado'],
            ['codigo' => '13910', 'valor' => 'Fabricación de tejidos de punto y ganchillo', 'status' => 'Desactivado'],
            ['codigo' => '13921', 'valor' => 'Fabricación de productos textiles para el hogar', 'status' => 'Desactivado'],
            ['codigo' => '13922', 'valor' => 'Sacos, bolsas y otros artículos textiles', 'status' => 'Desactivado'],
            ['codigo' => '13929', 'valor' => 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir ncp', 'status' => 'Desactivado'],
            ['codigo' => '13930', 'valor' => 'Fabricación de tapices y alfombras', 'status' => 'Desactivado'],
            ['codigo' => '13941', 'valor' => 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)', 'status' => 'Desactivado'],
            ['codigo' => '13942', 'valor' => 'Fabricación de redes de diversos materiales', 'status' => 'Desactivado'],
            ['codigo' => '13948', 'valor' => 'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)', 'status' => 'Desactivado'],
            ['codigo' => '13991', 'valor' => 'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir', 'status' => 'Desactivado'],
            ['codigo' => '13992', 'valor' => 'Servicio de bordados en artículos y prendas de tela', 'status' => 'Desactivado'],
            ['codigo' => '13999', 'valor' => 'Fabricación de productos textiles ncp', 'status' => 'Desactivado'],
            ['codigo' => '14101', 'valor' => 'Fabricación de ropa interior, para dormir y similares', 'status' => 'Desactivado'],
            ['codigo' => '14102', 'valor' => 'Fabricación de ropa para niños', 'status' => 'Desactivado'],
            ['codigo' => '14103', 'valor' => 'Fabricación de prendas de vestir para ambos sexos', 'status' => 'Desactivado'],
            ['codigo' => '14104', 'valor' => 'Confección de prendas a medida', 'status' => 'Desactivado'],
            ['codigo' => '14105', 'valor' => 'Fabricación de prendas de vestir para deportes', 'status' => 'Desactivado'],
            ['codigo' => '14106', 'valor' => 'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles', 'status' => 'Desactivado'],
            ['codigo' => '14108', 'valor' => 'Maquilado de prendas de vestir, accesorios y otros', 'status' => 'Desactivado'],
            ['codigo' => '14109', 'valor' => 'Fabricación de prendas y accesorios de vestir n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '14200', 'valor' => 'Fabricación de artículos de piel', 'status' => 'Desactivado'],
            ['codigo' => '14301', 'valor' => 'Fabricación de calcetines, calcetas, medias (panty house) y otros similares', 'status' => 'Desactivado'],
            ['codigo' => '14302', 'valor' => 'Fabricación de ropa interior de tejido de punto', 'status' => 'Desactivado'],
            ['codigo' => '14309', 'valor' => 'Fabricación de prendas de vestir de tejido de punto ncp', 'status' => 'Desactivado'],
            ['codigo' => '15110', 'valor' => 'Curtido y adobo de cueros; adobo y teñido de pieles', 'status' => 'Desactivado'],
            ['codigo' => '15121', 'valor' => 'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería', 'status' => 'Desactivado'],
            ['codigo' => '15122', 'valor' => 'Fabricación de monturas, accesorios y vainas talabartería', 'status' => 'Desactivado'],
            ['codigo' => '15123', 'valor' => 'Fabricación de artesanías principalmente de cuero natural y sintético', 'status' => 'Desactivado'],
            ['codigo' => '15128', 'valor' => 'Maquilado de artículos de cuero natural, sintético y de otros materiales', 'status' => 'Desactivado'],
            ['codigo' => '15201', 'valor' => 'Fabricación de calzado', 'status' => 'Desactivado'],
            ['codigo' => '15202', 'valor' => 'Fabricación de partes y accesorios de calzado', 'status' => 'Desactivado'],
            ['codigo' => '15208', 'valor' => 'Maquilado de partes y accesorios de calzado', 'status' => 'Desactivado'],
            ['codigo' => '16100', 'valor' => 'Aserradero y acepilladura de madera', 'status' => 'Desactivado'],
            ['codigo' => '16210', 'valor' => 'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción', 'status' => 'Desactivado'],
            ['codigo' => '16220', 'valor' => 'Fabricación de partes y piezas de carpintería para edificios y construcciones', 'status' => 'Desactivado'],
            ['codigo' => '16230', 'valor' => 'Fabricación de envases y recipientes de madera', 'status' => 'Desactivado'],
            ['codigo' => '16292', 'valor' => 'Fabricación de artesanías de madera, semillas, materiales trenzables', 'status' => 'Desactivado'],
            ['codigo' => '16299', 'valor' => 'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp', 'status' => 'Desactivado'],
            ['codigo' => '17010', 'valor' => 'Fabricación de pasta de madera, papel y cartón', 'status' => 'Desactivado'],
            ['codigo' => '17020', 'valor' => 'Fabricación de papel y cartón ondulado y envases de papel y cartón', 'status' => 'Desactivado'],
            ['codigo' => '17091', 'valor' => 'Fabricación de artículos de papel y cartón de uso personal y doméstico', 'status' => 'Desactivado'],
            ['codigo' => '17092', 'valor' => 'Fabricación de productos de papel ncp', 'status' => 'Desactivado'],
            ['codigo' => '18110', 'valor' => 'Impresión', 'status' => 'Desactivado'],
            ['codigo' => '18120', 'valor' => 'Servicios relacionados con la impresión', 'status' => 'Desactivado'],
            ['codigo' => '18200', 'valor' => 'Reproducción de grabaciones', 'status' => 'Desactivado'],
            ['codigo' => '19100', 'valor' => 'Fabricación de productos de hornos de coque', 'status' => 'Desactivado'],
            ['codigo' => '19201', 'valor' => 'Fabricación de combustible', 'status' => 'Desactivado'],
            ['codigo' => '19202', 'valor' => 'Fabricación de aceites y lubricantes', 'status' => 'Desactivado'],
            ['codigo' => '20111', 'valor' => 'Fabricación de materias primas para la fabricación de colorantes', 'status' => 'Desactivado'],
            ['codigo' => '20112', 'valor' => 'Fabricación de materiales curtientes', 'status' => 'Desactivado'],
            ['codigo' => '20113', 'valor' => 'Fabricación de gases industriales', 'status' => 'Desactivado'],
            ['codigo' => '20114', 'valor' => 'Fabricación de alcohol etílico', 'status' => 'Desactivado'],
            ['codigo' => '20119', 'valor' => 'Fabricación de sustancias químicas básicas', 'status' => 'Desactivado'],
            ['codigo' => '20120', 'valor' => 'Fabricación de abonos y fertilizantes', 'status' => 'Desactivado'],
            ['codigo' => '20130', 'valor' => 'Fabricación de plástico y caucho en formas primarias', 'status' => 'Desactivado'],
            ['codigo' => '20210', 'valor' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 'status' => 'Desactivado'],
            ['codigo' => '20220', 'valor' => 'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas', 'status' => 'Desactivado'],
            ['codigo' => '20231', 'valor' => 'Fabricación de jabones, detergentes y similares para limpieza', 'status' => 'Desactivado'],
            ['codigo' => '20232', 'valor' => 'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.', 'status' => 'Desactivado'],
            ['codigo' => '20291', 'valor' => 'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras', 'status' => 'Desactivado'],
            ['codigo' => '20292', 'valor' => 'Fabricación de productos pirotécnicos, explosivos y municiones', 'status' => 'Desactivado'],
            ['codigo' => '20299', 'valor' => 'Fabricación de productos químicos n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '20300', 'valor' => 'Fabricación de fibras artificiales', 'status' => 'Desactivado'],
            ['codigo' => '21001', 'valor' => 'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos', 'status' => 'Desactivado'],
            ['codigo' => '21008', 'valor' => 'Maquilado de medicamentos', 'status' => 'Desactivado'],
            ['codigo' => '22110', 'valor' => 'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas', 'status' => 'Desactivado'],
            ['codigo' => '22190', 'valor' => 'Fabricación de otros productos de caucho', 'status' => 'Desactivado'],
            ['codigo' => '22201', 'valor' => 'Fabricación de envases plásticos', 'status' => 'Desactivado'],
            ['codigo' => '22202', 'valor' => 'Fabricación de productos plásticos para uso personal o doméstico', 'status' => 'Desactivado'],
            ['codigo' => '22208', 'valor' => 'Maquila de plásticos', 'status' => 'Desactivado'],
            ['codigo' => '22209', 'valor' => 'Fabricación de productos plásticos n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '23101', 'valor' => 'Fabricación de vidrio', 'status' => 'Desactivado'],
            ['codigo' => '23102', 'valor' => 'Fabricación de recipientes y envases de vidrio', 'status' => 'Desactivado'],
            ['codigo' => '23108', 'valor' => 'Servicio de maquilado', 'status' => 'Desactivado'],
            ['codigo' => '23109', 'valor' => 'Fabricación de productos de vidrio ncp', 'status' => 'Desactivado'],
            ['codigo' => '23910', 'valor' => 'Fabricación de productos refractarios', 'status' => 'Desactivado'],
            ['codigo' => '23920', 'valor' => 'Fabricación de productos de arcilla para la construcción', 'status' => 'Desactivado'],
            ['codigo' => '23931', 'valor' => 'Fabricación de productos de cerámica y porcelana no refractaria', 'status' => 'Desactivado'],
            ['codigo' => '23932', 'valor' => 'Fabricación de productos de cerámica y porcelana ncp', 'status' => 'Desactivado'],
            ['codigo' => '23940', 'valor' => 'Fabricación de cemento, cal y yeso', 'status' => 'Desactivado'],
            ['codigo' => '23950', 'valor' => 'Fabricación de artículos de hormigón, cemento y yeso', 'status' => 'Desactivado'],
            ['codigo' => '23960', 'valor' => 'Corte, tallado y acabado de la piedra', 'status' => 'Desactivado'],
            ['codigo' => '23990', 'valor' => 'Fabricación de productos minerales no metálicos ncp', 'status' => 'Desactivado'],
            ['codigo' => '24100', 'valor' => 'Industrias básicas de hierro y acero', 'status' => 'Desactivado'],
            ['codigo' => '24200', 'valor' => 'Fabricación de productos primarios de metales preciosos y metales no ferrosos', 'status' => 'Desactivado'],
            ['codigo' => '24310', 'valor' => 'Fundición de hierro y acero', 'status' => 'Desactivado'],
            ['codigo' => '24320', 'valor' => 'Fundición de metales no ferrosos', 'status' => 'Desactivado'],
            ['codigo' => '25111', 'valor' => 'Fabricación de productos metálicos para uso estructural', 'status' => 'Desactivado'],
            ['codigo' => '25118', 'valor' => 'Servicio de maquila para la fabricación de estructuras metálicas', 'status' => 'Desactivado'],
            ['codigo' => '25120', 'valor' => 'Fabricación de tanques, depósitos y recipientes de metal', 'status' => 'Desactivado'],
            ['codigo' => '25130', 'valor' => 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', 'status' => 'Desactivado'],
            ['codigo' => '25200', 'valor' => 'Fabricación de armas y municiones', 'status' => 'Desactivado'],
            ['codigo' => '25910', 'valor' => 'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia', 'status' => 'Desactivado'],
            ['codigo' => '25920', 'valor' => 'Tratamiento y revestimiento de metales', 'status' => 'Desactivado'],
            ['codigo' => '25930', 'valor' => 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', 'status' => 'Desactivado'],
            ['codigo' => '25991', 'valor' => 'Fabricación de envases y artículos conexos de metal', 'status' => 'Desactivado'],
            ['codigo' => '25992', 'valor' => 'Fabricación de artículos metálicos de uso personal y/o doméstico', 'status' => 'Desactivado'],
            ['codigo' => '25999', 'valor' => 'Fabricación de productos elaborados de metal ncp', 'status' => 'Desactivado'],
            ['codigo' => '26100', 'valor' => 'Fabricación de componentes electrónicos', 'status' => 'Desactivado'],
            ['codigo' => '26200', 'valor' => 'Fabricación de computadoras y equipo conexo', 'status' => 'Desactivado'],
            ['codigo' => '26300', 'valor' => 'Fabricación de equipo de comunicaciones', 'status' => 'Desactivado'],
            ['codigo' => '26400', 'valor' => 'Fabricación de aparatos electrónicos de consumo para audio, video radio y televisión', 'status' => 'Desactivado'],
            ['codigo' => '26510', 'valor' => 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales', 'status' => 'Desactivado'],
            ['codigo' => '26520', 'valor' => 'Fabricación de relojes y piezas de relojes', 'status' => 'Desactivado'],
            ['codigo' => '26600', 'valor' => 'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico', 'status' => 'Desactivado'],
            ['codigo' => '26700', 'valor' => 'Fabricación de instrumentos ópticos y equipo fotográfico', 'status' => 'Desactivado'],
            ['codigo' => '26800', 'valor' => 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos', 'status' => 'Desactivado'],
            ['codigo' => '27100', 'valor' => 'Fabricación de motores, generadores y transformadores eléctricos', 'status' => 'Desactivado'],
            ['codigo' => '27200', 'valor' => 'Fabricación de pilas, baterías y acumuladores eléctricos', 'status' => 'Desactivado'],
            ['codigo' => '27310', 'valor' => 'Fabricación de hilos y cables eléctricos y de fibra óptica', 'status' => 'Desactivado'],
            ['codigo' => '27320', 'valor' => 'Fabricación de dispositivos de cableado', 'status' => 'Desactivado'],
            ['codigo' => '27400', 'valor' => 'Fabricación de aparatos eléctricos de iluminación', 'status' => 'Desactivado'],
            ['codigo' => '27500', 'valor' => 'Fabricación de aparatos de uso doméstico', 'status' => 'Desactivado'],
            ['codigo' => '27900', 'valor' => 'Fabricación de otros tipos de equipo eléctrico', 'status' => 'Desactivado'],
            ['codigo' => '28110', 'valor' => 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas', 'status' => 'Desactivado'],
            ['codigo' => '28120', 'valor' => 'Fabricación de equipos de potencia hidráulica y neumática', 'status' => 'Desactivado'],
            ['codigo' => '28130', 'valor' => 'Fabricación de otros tipos de bombas, compresores, grifos y válvulas', 'status' => 'Desactivado'],
            ['codigo' => '28140', 'valor' => 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', 'status' => 'Desactivado'],
            ['codigo' => '28150', 'valor' => 'Fabricación de hornos, hogares y quemadores industriales', 'status' => 'Desactivado'],
            ['codigo' => '28160', 'valor' => 'Fabricación de equipo de elevación y manipulación', 'status' => 'Desactivado'],
            ['codigo' => '28170', 'valor' => 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)', 'status' => 'Desactivado'],
            ['codigo' => '28180', 'valor' => 'Fabricación de herramientas manuales con motor', 'status' => 'Desactivado'],
            ['codigo' => '28190', 'valor' => 'Fabricación de otros tipos de maquinaria de uso general', 'status' => 'Desactivado'],
            ['codigo' => '28210', 'valor' => 'Fabricación de maquinaria agropecuaria y forestal', 'status' => 'Desactivado'],
            ['codigo' => '28220', 'valor' => 'Fabricación de máquinas herramienta para trabajar el metal', 'status' => 'Desactivado'],
            ['codigo' => '28230', 'valor' => 'Fabricación de maquinaria metalúrgica', 'status' => 'Desactivado'],
            ['codigo' => '28240', 'valor' => 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción', 'status' => 'Desactivado'],
            ['codigo' => '28250', 'valor' => 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 'status' => 'Desactivado'],
            ['codigo' => '28260', 'valor' => 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 'status' => 'Desactivado'],
            ['codigo' => '28290', 'valor' => 'Fabricación de otros tipos de maquinaria de uso especial', 'status' => 'Desactivado'],
            ['codigo' => '28291', 'valor' => 'Fabricación de maquinas de imprenta', 'status' => 'Desactivado'],
            ['codigo' => '28299', 'valor' => 'Fabricación de maquinaria de uso especial ncp', 'status' => 'Desactivado'],
            ['codigo' => '29100', 'valor' => 'Fabricación de vehículos automotores', 'status' => 'Desactivado'],
            ['codigo' => '29200', 'valor' => 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques', 'status' => 'Desactivado'],
            ['codigo' => '29300', 'valor' => 'Fabricación de partes, piezas (autopartes) y accesorios para vehículos automotores', 'status' => 'Desactivado'],
            ['codigo' => '30110', 'valor' => 'Construcción de barcos y estructuras flotantes', 'status' => 'Desactivado'],
            ['codigo' => '30120', 'valor' => 'Construcción de embarcaciones de recreo y deporte', 'status' => 'Desactivado'],
            ['codigo' => '30200', 'valor' => 'Fabricación de locomotoras y de material rodante para ferrocarriles', 'status' => 'Desactivado'],
            ['codigo' => '30300', 'valor' => 'Fabricación de aeronaves, naves espaciales y sus dispositivos conexos', 'status' => 'Desactivado'],
            ['codigo' => '30400', 'valor' => 'Fabricación de vehículos militares de combate', 'status' => 'Desactivado'],
            ['codigo' => '30910', 'valor' => 'Fabricación de motocicletas', 'status' => 'Desactivado'],
            ['codigo' => '30920', 'valor' => 'Fabricación de bicicletas y de sillones de ruedas para personas con discapacidad', 'status' => 'Desactivado'],
            ['codigo' => '30990', 'valor' => 'Fabricación de otro equipo de transporte n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '31001', 'valor' => 'Fabricación de muebles', 'status' => 'Desactivado'],
            ['codigo' => '31002', 'valor' => 'Fabricación de muebles y otros productos de madera a medida', 'status' => 'Desactivado'],
            ['codigo' => '31008', 'valor' => 'Servicios de maquilado de muebles', 'status' => 'Desactivado'],
            ['codigo' => '31009', 'valor' => 'Fabricación de muebles ncp', 'status' => 'Desactivado'],
            ['codigo' => '32110', 'valor' => 'Fabricación de joyas platerías y joyerías', 'status' => 'Desactivado'],

            ['codigo' => '32120', 'valor' => 'Fabricación de joyas de imitación (fantasía) y artículos conexos', 'status' => 'Desactivado'],
            
            ['codigo' => '32200', 'valor' => 'Fabricación de instrumentos musicales', 'status' => 'Desactivado'],
            ['codigo' => '32300', 'valor' => 'Fabricación de artículos y equipo para la práctica del deporte', 'status' => 'Desactivado'],
            ['codigo' => '32400', 'valor' => 'Fabricación de juegos y juguetes', 'status' => 'Desactivado'],
            ['codigo' => '32500', 'valor' => 'Fabricación de instrumentos y materiales médicos y odontológicos', 'status' => 'Desactivado'],
            ['codigo' => '32900', 'valor' => 'Otras industrias manufactureras n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '33110', 'valor' => 'Mantenimiento y reparación especializado de productos elaborados en metal', 'status' => 'Desactivado'],
            ['codigo' => '33120', 'valor' => 'Mantenimiento y reparación especializado de maquinaria de uso general', 'status' => 'Desactivado'],
            ['codigo' => '33130', 'valor' => 'Mantenimiento y reparación especializado de equipo electrónico y óptico', 'status' => 'Desactivado'],
            ['codigo' => '33140', 'valor' => 'Mantenimiento y reparación especializado de equipo eléctrico', 'status' => 'Desactivado'],
            ['codigo' => '33150', 'valor' => 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas', 'status' => 'Desactivado'],
            ['codigo' => '33190', 'valor' => 'Mantenimiento y reparación especializado de otro tipo de equipo', 'status' => 'Desactivado'],
            ['codigo' => '33200', 'valor' => 'Instalación de maquinaria y equipo industrial', 'status' => 'Desactivado'],
            ['codigo' => '35101', 'valor' => 'Generación de energía eléctrica', 'status' => 'Desactivado'],
            ['codigo' => '35102', 'valor' => 'Transmisión de energía eléctrica', 'status' => 'Desactivado'],
            ['codigo' => '35103', 'valor' => 'Distribución de energía eléctrica', 'status' => 'Desactivado'],
            ['codigo' => '35104', 'valor' => 'Comercialización de energía eléctrica', 'status' => 'Desactivado'],
            ['codigo' => '35105', 'valor' => 'Generación, transmisión y distribución de energía eléctrica', 'status' => 'Desactivado'],
            ['codigo' => '35201', 'valor' => 'Distribución de gas natural', 'status' => 'Desactivado'],
            ['codigo' => '35202', 'valor' => 'Distribución de gases combustibles por tuberías', 'status' => 'Desactivado'],
            ['codigo' => '35300', 'valor' => 'Suministro de vapor y aire acondicionado', 'status' => 'Desactivado'],
            ['codigo' => '36000', 'valor' => 'Captación, tratamiento y distribución de agua', 'status' => 'Desactivado'],
            ['codigo' => '37000', 'valor' => 'Evacuación de aguas residuales', 'status' => 'Desactivado'],
            ['codigo' => '38110', 'valor' => 'Recolección de desechos no peligrosos', 'status' => 'Desactivado'],
            ['codigo' => '38120', 'valor' => 'Recolección de desechos peligrosos', 'status' => 'Desactivado'],
            ['codigo' => '38210', 'valor' => 'Tratamiento y disposición de desechos no peligrosos', 'status' => 'Desactivado'],
            ['codigo' => '38220', 'valor' => 'Tratamiento y disposición de desechos peligrosos', 'status' => 'Desactivado'],
            ['codigo' => '38301', 'valor' => 'Recuperación de materiales metálicos reciclables', 'status' => 'Desactivado'],
            ['codigo' => '38302', 'valor' => 'Recuperación de materiales no metálicos reciclables', 'status' => 'Desactivado'],
            ['codigo' => '39000', 'valor' => 'Actividades de saneamiento y otros servicios de gestión de desechos', 'status' => 'Desactivado'],
            ['codigo' => '41000', 'valor' => 'Construcción de edificios', 'status' => 'Desactivado'],
            ['codigo' => '42100', 'valor' => 'Construcción de carreteras y vías férreas', 'status' => 'Desactivado'],
            ['codigo' => '42200', 'valor' => 'Construcción de proyectos de servicio público', 'status' => 'Desactivado'],
            ['codigo' => '42900', 'valor' => 'Construcción de otros proyectos de ingeniería civil', 'status' => 'Desactivado'],
            ['codigo' => '43110', 'valor' => 'Demolición', 'status' => 'Desactivado'],
            ['codigo' => '43120', 'valor' => 'Preparación del terreno', 'status' => 'Desactivado'],
            ['codigo' => '43210', 'valor' => 'Instalaciones eléctricas', 'status' => 'Desactivado'],
            ['codigo' => '43220', 'valor' => 'Instalación de sistemas de fontanería, calefacción y aire acondicionado', 'status' => 'Desactivado'],
            ['codigo' => '43290', 'valor' => 'Otras instalaciones para edificios', 'status' => 'Desactivado'],
            ['codigo' => '43300', 'valor' => 'Terminación de edificios', 'status' => 'Desactivado'],
            ['codigo' => '43900', 'valor' => 'Otras actividades especializadas de construcción', 'status' => 'Desactivado'],
            ['codigo' => '45101', 'valor' => 'Venta de vehículos automotores', 'status' => 'Desactivado'],
            ['codigo' => '45102', 'valor' => 'Mantenimiento y reparación de vehículos automotores', 'status' => 'Desactivado'],
            ['codigo' => '45103', 'valor' => 'Venta de partes, piezas y accesorios para vehículos automotores', 'status' => 'Desactivado'],
            ['codigo' => '45104', 'valor' => 'Lavado, engrase y limpieza de vehículos automotores', 'status' => 'Desactivado'],
            ['codigo' => '45200', 'valor' => 'Mantenimiento y reparación de motocicletas y sus partes y piezas', 'status' => 'Desactivado'],
            ['codigo' => '45300', 'valor' => 'Venta de partes, piezas y accesorios para motocicletas', 'status' => 'Desactivado'],
            ['codigo' => '46101', 'valor' => 'Intermediación en la venta de productos agrícolas, materias primas, animales vivos, alimentos, bebidas y tabaco', 'status' => 'Desactivado'],
            ['codigo' => '46102', 'valor' => 'Intermediación en la venta de productos textiles, prendas de vestir, calzado, artículos de cuero y productos de marroquinería', 'status' => 'Desactivado'],
            ['codigo' => '46103', 'valor' => 'Intermediación en la venta de combustibles, minerales, metales y productos químicos industriales', 'status' => 'Desactivado'],
            ['codigo' => '46104', 'valor' => 'Intermediación en la venta de productos de la madera, materiales de construcción y aparatos sanitarios', 'status' => 'Desactivado'],
            ['codigo' => '46105', 'valor' => 'Intermediación en la venta de maquinaria, equipo, embarcaciones y aeronaves', 'status' => 'Desactivado'],
            ['codigo' => '46109', 'valor' => 'Intermediación en la venta de otros productos', 'status' => 'Desactivado'],
            ['codigo' => '46200', 'valor' => 'Venta al por mayor de productos agrícolas y alimentos para animales', 'status' => 'Desactivado'],
            ['codigo' => '46301', 'valor' => 'Venta al por mayor de carne y productos cárnicos', 'status' => 'Desactivado'],
            ['codigo' => '46302', 'valor' => 'Venta al por mayor de productos lácteos, huevos, aceites y grasas comestibles', 'status' => 'Desactivado'],
            ['codigo' => '46303', 'valor' => 'Venta al por mayor de frutas y hortalizas', 'status' => 'Desactivado'],
            ['codigo' => '46304', 'valor' => 'Venta al por mayor de bebidas y tabaco', 'status' => 'Desactivado'],
            ['codigo' => '46305', 'valor' => 'Venta al por mayor de azúcar, chocolate y confitería', 'status' => 'Desactivado'],
            ['codigo' => '46306', 'valor' => 'Venta al por mayor de café, té, cacao y especias', 'status' => 'Desactivado'],
            ['codigo' => '46309', 'valor' => 'Venta al por mayor de otros productos alimenticios n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '46411', 'valor' => 'Venta al por mayor de productos textiles', 'status' => 'Desactivado'],
            ['codigo' => '46412', 'valor' => 'Venta al por mayor de prendas de vestir', 'status' => 'Desactivado'],
            ['codigo' => '46413', 'valor' => 'Venta al por mayor de calzado', 'status' => 'Desactivado'],
            ['codigo' => '46414', 'valor' => 'Venta al por mayor de artículos de cuero y marroquinería', 'status' => 'Desactivado'],
            ['codigo' => '46421', 'valor' => 'Venta al por mayor de productos farmacéuticos', 'status' => 'Desactivado'],
            ['codigo' => '46422', 'valor' => 'Venta al por mayor de productos cosméticos y de perfumería', 'status' => 'Desactivado'],
            ['codigo' => '46431', 'valor' => 'Venta al por mayor de aparatos y equipos eléctricos', 'status' => 'Desactivado'],
            ['codigo' => '46432', 'valor' => 'Venta al por mayor de equipos electrónicos y de telecomunicaciones y sus partes', 'status' => 'Desactivado'],
            ['codigo' => '46439', 'valor' => 'Venta al por mayor de otros equipos y accesorios electrónicos', 'status' => 'Desactivado'],
            ['codigo' => '46440', 'valor' => 'Venta al por mayor de productos de ferretería, fontanería y calefacción', 'status' => 'Desactivado'],
            ['codigo' => '46450', 'valor' => 'Venta al por mayor de muebles y artículos para el hogar', 'status' => 'Desactivado'],
            ['codigo' => '46460', 'valor' => 'Venta al por mayor de artículos de relojería y joyería', 'status' => 'Desactivado'],
            ['codigo' => '46491', 'valor' => 'Venta al por mayor de material de oficina y papelería', 'status' => 'Desactivado'],
            ['codigo' => '46492', 'valor' => 'Venta al por mayor de instrumentos musicales', 'status' => 'Desactivado'],
            ['codigo' => '46493', 'valor' => 'Venta al por mayor de juegos y juguetes', 'status' => 'Desactivado'],
            ['codigo' => '46494', 'valor' => 'Venta al por mayor de equipos deportivos', 'status' => 'Desactivado'],
            ['codigo' => '46495', 'valor' => 'Venta al por mayor de artículos de uso doméstico n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '46510', 'valor' => 'Venta al por mayor de maquinaria, equipo y materiales agropecuarios', 'status' => 'Desactivado'],
            ['codigo' => '46520', 'valor' => 'Venta al por mayor de maquinaria y equipo para la minería, construcción y la ingeniería civil', 'status' => 'Desactivado'],
            ['codigo' => '46530', 'valor' => 'Venta al por mayor de maquinaria y equipo para la industria textil y de la confección', 'status' => 'Desactivado'],
            ['codigo' => '46590', 'valor' => 'Venta al por mayor de otros tipos de maquinaria y equipo', 'status' => 'Desactivado'],
            ['codigo' => '46610', 'valor' => 'Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos', 'status' => 'Desactivado'],
            ['codigo' => '46620', 'valor' => 'Venta al por mayor de metales y minerales metálicos', 'status' => 'Desactivado'],
            ['codigo' => '46630', 'valor' => 'Venta al por mayor de materiales de construcción, artículos de ferretería y equipo y materiales de fontanería y calefacción', 'status' => 'Desactivado'],
            ['codigo' => '46691', 'valor' => 'Venta al por mayor de desperdicios y desechos metálicos y no metálicos n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '46692', 'valor' => 'Venta al por mayor de envases y embalajes', 'status' => 'Desactivado'],
            ['codigo' => '46699', 'valor' => 'Venta al por mayor de productos diversos n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '46901', 'valor' => 'Comercio al por mayor no especializado con surtido principalmente de productos alimenticios, bebidas y tabaco', 'status' => 'Desactivado'],
            ['codigo' => '46909', 'valor' => 'Comercio al por mayor no especializado', 'status' => 'Desactivado'],
            ['codigo' => '47110', 'valor' => 'Venta al por menor en comercios no especializados con surtido principalmente de productos alimenticios, bebidas y tabaco', 'status' => 'Desactivado'],
            ['codigo' => '47190', 'valor' => 'Venta al por menor en comercios no especializados', 'status' => 'Desactivado'],
            ['codigo' => '47211', 'valor' => 'Venta al por menor de carnes (incluye aves de corral) y productos cárnicos', 'status' => 'Desactivado'],
            ['codigo' => '47212', 'valor' => 'Venta al por menor de pescados y otros productos acuáticos', 'status' => 'Desactivado'],
            ['codigo' => '47213', 'valor' => 'Venta al por menor de frutas y hortalizas', 'status' => 'Desactivado'],
            ['codigo' => '47214', 'valor' => 'Venta al por menor de productos lácteos, huevos y otros productos comestibles n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '47221', 'valor' => 'Venta al por menor de pan y productos de panadería', 'status' => 'Desactivado'],
            ['codigo' => '47222', 'valor' => 'Venta al por menor de confites, dulces, y similares', 'status' => 'Desactivado'],
            ['codigo' => '47223', 'valor' => 'Venta al por menor de helados', 'status' => 'Desactivado'],
            ['codigo' => '47229', 'valor' => 'Venta al por menor de otros productos alimenticios n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '47230', 'valor' => 'Venta al por menor de bebidas en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47240', 'valor' => 'Venta al por menor de productos de tabaco en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47300', 'valor' => 'Venta al por menor de combustible para vehículos automotores en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47411', 'valor' => 'Venta al por menor de computadoras, equipo periférico y programas de informática en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47412', 'valor' => 'Venta al por menor de equipo de telecomunicaciones en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47420', 'valor' => 'Venta al por menor de equipos de audio y video en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47510', 'valor' => 'Venta al por menor de textiles en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47520', 'valor' => 'Venta al por menor de artículos de ferretería, fontanería y calefacción en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47530', 'valor' => 'Venta al por menor de alfombras, tapices y revestimientos de paredes y pisos en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47540', 'valor' => 'Venta al por menor de aparatos electrodomésticos y de gas en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47590', 'valor' => 'Venta al por menor de muebles, artículos para el hogar y materiales de construcción en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47610', 'valor' => 'Venta al por menor de libros en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47620', 'valor' => 'Venta al por menor de periódicos y artículos de papelería en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47630', 'valor' => 'Venta al por menor de grabaciones de música y video en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47640', 'valor' => 'Venta al por menor de artículos y equipo para la práctica del deporte en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47650', 'valor' => 'Venta al por menor de juegos y juguetes en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47710', 'valor' => 'Venta al por menor de prendas de vestir en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47721', 'valor' => 'Venta al por menor de productos farmacéuticos y medicinales', 'status' => 'Desactivado'],
            ['codigo' => '47722', 'valor' => 'Venta al por menor de productos cosméticos y de perfumería en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47730', 'valor' => 'Venta al por menor de artículos de relojería y joyería en comercios especializados', 'status' => 'Desactivado'],
            ['codigo' => '47740', 'valor' => 'Venta al por menor de artículos usados', 'status' => 'Desactivado'],
            ['codigo' => '47781', 'valor' => 'Venta al por menor de flores y plantas naturales', 'status' => 'Desactivado'],
            ['codigo' => '47782', 'valor' => 'Venta al por menor de animales domésticos', 'status' => 'Desactivado'],
            ['codigo' => '47783', 'valor' => 'Venta al por menor de alimentos para animales domésticos', 'status' => 'Desactivado'],
            ['codigo' => '47789', 'valor' => 'Venta al por menor de otros productos nuevos en comercios especializados n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '47810', 'valor' => 'Venta al por menor en puestos de venta y mercados de alimentos, bebidas y tabaco', 'status' => 'Desactivado'],
            ['codigo' => '47820', 'valor' => 'Venta al por menor en puestos de venta y mercados de textiles, prendas de vestir y calzado', 'status' => 'Desactivado'],
            ['codigo' => '47890', 'valor' => 'Venta al por menor en puestos de venta y mercados de otros productos', 'status' => 'Desactivado'],
            ['codigo' => '47910', 'valor' => 'Venta al por menor realizada por correspondencia o por Internet', 'status' => 'Desactivado'],
            ['codigo' => '47990', 'valor' => 'Otras formas de venta al por menor no realizada en comercios, puestos de venta o mercados', 'status' => 'Desactivado'],
            ['codigo' => '49110', 'valor' => 'Transporte ferroviario de pasajeros', 'status' => 'Desactivado'],
            ['codigo' => '49120', 'valor' => 'Transporte ferroviario de carga', 'status' => 'Desactivado'],
            ['codigo' => '49211', 'valor' => 'Transporte de pasajeros vía terrestre', 'status' => 'Desactivado'],
            ['codigo' => '49212', 'valor' => 'Transporte de carga por carretera', 'status' => 'Desactivado'],
            ['codigo' => '49213', 'valor' => 'Transporte por taxis', 'status' => 'Desactivado'],
            ['codigo' => '49219', 'valor' => 'Transporte por otros tipos de vehículos terrestres', 'status' => 'Desactivado'],
            ['codigo' => '49300', 'valor' => 'Transporte por tuberías', 'status' => 'Desactivado'],
            ['codigo' => '50111', 'valor' => 'Transporte marítimo y de cabotaje de pasajeros', 'status' => 'Desactivado'],
            ['codigo' => '50112', 'valor' => 'Transporte marítimo y de cabotaje de carga', 'status' => 'Desactivado'],
            ['codigo' => '50210', 'valor' => 'Transporte de pasajeros por vías navegables interiores', 'status' => 'Desactivado'],
            ['codigo' => '50220', 'valor' => 'Transporte de carga por vías navegables interiores', 'status' => 'Desactivado'],
            ['codigo' => '51100', 'valor' => 'Transporte aéreo de pasajeros', 'status' => 'Desactivado'],
            ['codigo' => '51200', 'valor' => 'Transporte aéreo de carga', 'status' => 'Desactivado'],
            ['codigo' => '52100', 'valor' => 'Almacenamiento y depósito', 'status' => 'Desactivado'],
            ['codigo' => '52210', 'valor' => 'Servicios anexos para el transporte terrestre', 'status' => 'Desactivado'],
            ['codigo' => '52220', 'valor' => 'Servicios anexos para el transporte acuático', 'status' => 'Desactivado'],
            ['codigo' => '52230', 'valor' => 'Servicios anexos para el transporte aéreo', 'status' => 'Desactivado'],
            ['codigo' => '52240', 'valor' => 'Manipulación de la carga', 'status' => 'Desactivado'],
            ['codigo' => '52290', 'valor' => 'Otras actividades anexas para el transporte', 'status' => 'Desactivado'],
            ['codigo' => '53100', 'valor' => 'Actividades postales nacionales', 'status' => 'Desactivado'],
            ['codigo' => '53200', 'valor' => 'Actividades de mensajería', 'status' => 'Desactivado'],
            ['codigo' => '55101', 'valor' => 'Hoteles con restaurante', 'status' => 'Desactivado'],
            ['codigo' => '55102', 'valor' => 'Hoteles sin restaurante', 'status' => 'Desactivado'],
            ['codigo' => '55103', 'valor' => 'Alojamientos turísticos de corta estancia', 'status' => 'Desactivado'],
            ['codigo' => '55104', 'valor' => 'Campamentos, parques para vehículos recreacionales y parques de recreo', 'status' => 'Desactivado'],
            ['codigo' => '55200', 'valor' => 'Actividades de hospedaje n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '56100', 'valor' => 'Actividades de restaurantes y de servicio móvil de comidas', 'status' => 'Desactivado'],
            ['codigo' => '56210', 'valor' => 'Provisión de alimentos preparados para eventos', 'status' => 'Desactivado'],
            ['codigo' => '56290', 'valor' => 'Otros servicios de comidas', 'status' => 'Desactivado'],
            ['codigo' => '56301', 'valor' => 'Expendio de bebidas en bares', 'status' => 'Desactivado'],
            ['codigo' => '56302', 'valor' => 'Expendio de bebidas en cantinas', 'status' => 'Desactivado'],
            ['codigo' => '56303', 'valor' => 'Expendio de bebidas en discotecas', 'status' => 'Desactivado'],
            ['codigo' => '56304', 'valor' => 'Expendio de bebidas en centros nocturnos', 'status' => 'Desactivado'],
            ['codigo' => '56305', 'valor' => 'Expendio de bebidas en casinos', 'status' => 'Desactivado'],
            ['codigo' => '56306', 'valor' => 'Expendio de bebidas en clubes sociales', 'status' => 'Desactivado'],
            ['codigo' => '56307', 'valor' => 'Expendio de bebidas en restaurantes y similares', 'status' => 'Desactivado'],
            ['codigo' => '56308', 'valor' => 'Expendio de bebidas en pulperías y tiendas de barrio', 'status' => 'Desactivado'],
            ['codigo' => '56309', 'valor' => 'Expendio de bebidas en ferias y eventos similares', 'status' => 'Desactivado'],
            ['codigo' => '56310', 'valor' => 'Expendio de bebidas en lugares de esparcimiento y recreo', 'status' => 'Desactivado'],
            ['codigo' => '58110', 'valor' => 'Edición de libros', 'status' => 'Desactivado'],
            ['codigo' => '58120', 'valor' => 'Edición de directorios y listas de correo', 'status' => 'Desactivado'],
            ['codigo' => '58130', 'valor' => 'Edición de periódicos', 'status' => 'Desactivado'],
            ['codigo' => '58140', 'valor' => 'Edición de revistas y otras publicaciones periódicas', 'status' => 'Desactivado'],
            ['codigo' => '58190', 'valor' => 'Otras actividades de edición', 'status' => 'Desactivado'],
            ['codigo' => '58200', 'valor' => 'Edición de programas de informática', 'status' => 'Desactivado'],
            ['codigo' => '59110', 'valor' => 'Actividades de producción de películas cinematográficas, videos y programas de televisión', 'status' => 'Desactivado'],
            ['codigo' => '59120', 'valor' => 'Actividades de postproducción de películas cinematográficas, videos y programas de televisión', 'status' => 'Desactivado'],
            ['codigo' => '59130', 'valor' => 'Actividades de distribución de películas cinematográficas, videos y programas de televisión', 'status' => 'Desactivado'],
            ['codigo' => '59140', 'valor' => 'Actividades de exhibición de películas cinematográficas', 'status' => 'Desactivado'],
            ['codigo' => '59200', 'valor' => 'Actividades de grabación de sonido y edición de música', 'status' => 'Desactivado'],
            ['codigo' => '60100', 'valor' => 'Actividades de programación y transmisiones de radio', 'status' => 'Desactivado'],
            ['codigo' => '60200', 'valor' => 'Actividades de programación y transmisiones de televisión', 'status' => 'Desactivado'],
            ['codigo' => '61100', 'valor' => 'Actividades de telecomunicaciones alámbricas', 'status' => 'Desactivado'],
            ['codigo' => '61200', 'valor' => 'Actividades de telecomunicaciones inalámbricas', 'status' => 'Desactivado'],
            ['codigo' => '61300', 'valor' => 'Actividades de telecomunicaciones por satélite', 'status' => 'Desactivado'],
            ['codigo' => '61900', 'valor' => 'Otras actividades de telecomunicaciones', 'status' => 'Desactivado'],
            ['codigo' => '62010', 'valor' => 'Actividades de programación y consultoría informática', 'status' => 'Desactivado'],
            ['codigo' => '62020', 'valor' => 'Actividades de consultoría informática y gestión de instalaciones informáticas', 'status' => 'Desactivado'],
            ['codigo' => '62030', 'valor' => 'Gestión de instalaciones informáticas', 'status' => 'Desactivado'],
            ['codigo' => '62090', 'valor' => 'Otras actividades de tecnologías de la información y servicios informáticos', 'status' => 'Desactivado'],
            ['codigo' => '63110', 'valor' => 'Proceso de datos, alojamiento en la nube (Cloud computing) y actividades conexas', 'status' => 'Desactivado'],
            ['codigo' => '63120', 'valor' => 'Portales web', 'status' => 'Desactivado'],
            ['codigo' => '63910', 'valor' => 'Actividades de agencias de noticias', 'status' => 'Desactivado'],
            ['codigo' => '63990', 'valor' => 'Otras actividades de servicio de información', 'status' => 'Desactivado'],
            ['codigo' => '64110', 'valor' => 'Banca central', 'status' => 'Desactivado'],
            ['codigo' => '64191', 'valor' => 'Bancos comerciales', 'status' => 'Desactivado'],
            ['codigo' => '64192', 'valor' => 'Instituciones financieras especializadas en otorgar créditos', 'status' => 'Desactivado'],
            ['codigo' => '64193', 'valor' => 'Instituciones financieras especializadas en otorgar microcréditos', 'status' => 'Desactivado'],
            ['codigo' => '64194', 'valor' => 'Bancos de inversión', 'status' => 'Desactivado'],
            ['codigo' => '64201', 'valor' => 'Actividades de sociedades de ahorro y crédito', 'status' => 'Desactivado'],
            ['codigo' => '64202', 'valor' => 'Actividades de fondos de inversión', 'status' => 'Desactivado'],
            ['codigo' => '64203', 'valor' => 'Actividades de fideicomisos, fondos y entidades financieras similares', 'status' => 'Desactivado'],
            ['codigo' => '64204', 'valor' => 'Actividades de financieras de uso limitado', 'status' => 'Desactivado'],
            ['codigo' => '64300', 'valor' => 'Fondos y sociedades de inversión y entidades financieras similares', 'status' => 'Desactivado'],
            ['codigo' => '64910', 'valor' => 'Arrendamiento financiero', 'status' => 'Desactivado'],
            ['codigo' => '64921', 'valor' => 'Actividades de fondos y sociedades de inversión', 'status' => 'Desactivado'],
            ['codigo' => '64922', 'valor' => 'Actividades de fideicomisos, fondos y entidades financieras similares', 'status' => 'Desactivado'],
            ['codigo' => '64929', 'valor' => 'Otras actividades de concesión de crédito', 'status' => 'Desactivado'],
            ['codigo' => '64990', 'valor' => 'Otras actividades de servicios financieros, excepto las de seguros y pensiones', 'status' => 'Desactivado'],
            ['codigo' => '65111', 'valor' => 'Servicios de seguros de vida', 'status' => 'Desactivado'],
            ['codigo' => '65112', 'valor' => 'Servicios de seguros generales', 'status' => 'Desactivado'],
            ['codigo' => '65121', 'valor' => 'Actividades de seguros y fondos de pensiones excepto seguros sociales obligatorios', 'status' => 'Desactivado'],
            ['codigo' => '65122', 'valor' => 'Servicios de fondos de pensiones excepto los de la seguridad social', 'status' => 'Desactivado'],
            ['codigo' => '65200', 'valor' => 'Reaseguros', 'status' => 'Desactivado'],
            ['codigo' => '65300', 'valor' => 'Fondos de pensiones', 'status' => 'Desactivado'],
            ['codigo' => '66110', 'valor' => 'Administración de mercados financieros', 'status' => 'Desactivado'],
            ['codigo' => '66120', 'valor' => 'Actividades de corredores de bolsa y operadores de mercados financieros', 'status' => 'Desactivado'],
            ['codigo' => '66190', 'valor' => 'Otras actividades auxiliares de servicios financieros', 'status' => 'Desactivado'],
            ['codigo' => '66210', 'valor' => 'Actividades de agentes y corredores de seguros', 'status' => 'Desactivado'],
            ['codigo' => '66220', 'valor' => 'Actividades de agentes de seguros y afines', 'status' => 'Desactivado'],
            ['codigo' => '66290', 'valor' => 'Otras actividades auxiliares de servicios de seguros y fondos de pensiones', 'status' => 'Desactivado'],
            ['codigo' => '66300', 'valor' => 'Actividades de gestión de fondos', 'status' => 'Desactivado'],
            ['codigo' => '68101', 'valor' => 'Actividades inmobiliarias con bienes propios o arrendados', 'status' => 'Desactivado'],
            ['codigo' => '81100', 'valor' => 'Actividades combinadas de apoyo a instalaciones', 'status' => 'Desactivado'],
            ['codigo' => '81210', 'valor' => 'Actividades de limpieza general de edificios', 'status' => 'Desactivado'],
            ['codigo' => '81290', 'valor' => 'Otras actividades de limpieza', 'status' => 'Desactivado'],
            ['codigo' => '81300', 'valor' => 'Actividades de jardinería y mantenimiento de paisajes', 'status' => 'Desactivado'],
            ['codigo' => '82110', 'valor' => 'Servicios administrativos combinados', 'status' => 'Desactivado'],
            ['codigo' => '82190', 'valor' => 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficinas', 'status' => 'Desactivado'],
            ['codigo' => '82200', 'valor' => 'Actividades de centros de llamadas', 'status' => 'Desactivado'],
            ['codigo' => '82300', 'valor' => 'Organización de convenciones y ferias comerciales', 'status' => 'Desactivado'],
            ['codigo' => '82910', 'valor' => 'Actividades de agencias de cobro y agencias de información comercial', 'status' => 'Desactivado'],
            ['codigo' => '82920', 'valor' => 'Actividades de envase y empaque', 'status' => 'Desactivado'],
            ['codigo' => '82990', 'valor' => 'Otras actividades de servicio de apoyo a las empresas n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '84110', 'valor' => 'Actividades legislativas', 'status' => 'Desactivado'],
            ['codigo' => '84120', 'valor' => 'Actividades ejecutivas', 'status' => 'Desactivado'],
            ['codigo' => '84130', 'valor' => 'Regulación y facilitación de la actividad económica', 'status' => 'Desactivado'],
            ['codigo' => '84140', 'valor' => 'Actividades de prestación de servicios a la comunidad en general', 'status' => 'Desactivado'],
            ['codigo' => '84210', 'valor' => 'Relaciones exteriores', 'status' => 'Desactivado'],
            ['codigo' => '84220', 'valor' => 'Servicios de defensa', 'status' => 'Desactivado'],
            ['codigo' => '84230', 'valor' => 'Justicia y tribunales', 'status' => 'Desactivado'],
            ['codigo' => '84240', 'valor' => 'Orden público y seguridad', 'status' => 'Desactivado'],
            ['codigo' => '84250', 'valor' => 'Actividades de protección civil', 'status' => 'Desactivado'],
            ['codigo' => '84300', 'valor' => 'Actividades de planes de seguridad social de afiliación obligatoria', 'status' => 'Desactivado'],
            ['codigo' => '85100', 'valor' => 'Educación preprimaria', 'status' => 'Desactivado'],
            ['codigo' => '85200', 'valor' => 'Educación primaria', 'status' => 'Desactivado'],
            ['codigo' => '85310', 'valor' => 'Educación secundaria de formación general', 'status' => 'Desactivado'],
            ['codigo' => '85320', 'valor' => 'Educación secundaria de formación técnica y profesional', 'status' => 'Desactivado'],
            ['codigo' => '85410', 'valor' => 'Educación superior de formación universitaria', 'status' => 'Desactivado'],
            ['codigo' => '85420', 'valor' => 'Educación superior de formación técnica y profesional', 'status' => 'Desactivado'],
            ['codigo' => '85510', 'valor' => 'Actividades de enseñanza de idiomas', 'status' => 'Desactivado'],
            ['codigo' => '85520', 'valor' => 'Actividades de enseñanza cultural', 'status' => 'Desactivado'],
            ['codigo' => '85530', 'valor' => 'Actividades de enseñanza deportiva y recreativa', 'status' => 'Desactivado'],
            ['codigo' => '85590', 'valor' => 'Otras actividades de enseñanza n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '85600', 'valor' => 'Actividades de apoyo a la educación', 'status' => 'Desactivado'],
            ['codigo' => '86100', 'valor' => 'Actividades de hospitales', 'status' => 'Desactivado'],
            ['codigo' => '86200', 'valor' => 'Actividades de médicos y odontólogos', 'status' => 'Desactivado'],
            ['codigo' => '86901', 'valor' => 'Actividades de centros de diagnóstico', 'status' => 'Desactivado'],
            ['codigo' => '86902', 'valor' => 'Actividades de laboratorios de análisis clínicos', 'status' => 'Desactivado'],
            ['codigo' => '86903', 'valor' => 'Actividades de bancos de sangre', 'status' => 'Desactivado'],
            ['codigo' => '86909', 'valor' => 'Otras actividades de atención de la salud humana', 'status' => 'Desactivado'],
            ['codigo' => '87100', 'valor' => 'Actividades de atención en instituciones para personas con discapacidad mental y abuso de sustancias', 'status' => 'Desactivado'],
            ['codigo' => '87200', 'valor' => 'Actividades de atención en instituciones para personas con discapacidad', 'status' => 'Desactivado'],
            ['codigo' => '87300', 'valor' => 'Actividades de atención en instituciones para personas mayores', 'status' => 'Desactivado'],
            ['codigo' => '87900', 'valor' => 'Otras actividades de atención en instituciones', 'status' => 'Desactivado'],
            ['codigo' => '88100', 'valor' => 'Actividades de servicios sociales sin alojamiento para personas mayores y discapacitadas', 'status' => 'Desactivado'],
            ['codigo' => '88900', 'valor' => 'Otras actividades de servicios sociales sin alojamiento', 'status' => 'Desactivado'],
            ['codigo' => '90000', 'valor' => 'Actividades creativas, artísticas y de entretenimiento', 'status' => 'Desactivado'],
            ['codigo' => '91010', 'valor' => 'Actividades de bibliotecas y archivos', 'status' => 'Desactivado'],
            ['codigo' => '91020', 'valor' => 'Actividades de museos', 'status' => 'Desactivado'],
            ['codigo' => '91030', 'valor' => 'Actividades de conservación de lugares y edificios históricos', 'status' => 'Desactivado'],
            ['codigo' => '91040', 'valor' => 'Actividades de jardines botánicos, zoológicos y reservas naturales', 'status' => 'Desactivado'],
            ['codigo' => '92000', 'valor' => 'Actividades de juegos de azar y apuestas', 'status' => 'Desactivado'],
            ['codigo' => '93110', 'valor' => 'Actividades de instalaciones deportivas', 'status' => 'Desactivado'],
            ['codigo' => '93120', 'valor' => 'Actividades de clubes deportivos', 'status' => 'Desactivado'],
            ['codigo' => '93190', 'valor' => 'Otras actividades deportivas', 'status' => 'Desactivado'],
            ['codigo' => '93210', 'valor' => 'Actividades de parques de atracciones y parques temáticos', 'status' => 'Desactivado'],
            ['codigo' => '93290', 'valor' => 'Otras actividades recreativas y de entretenimiento n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '94110', 'valor' => 'Actividades de asociaciones empresariales y patronales', 'status' => 'Desactivado'],
            ['codigo' => '94120', 'valor' => 'Actividades de asociaciones profesionales', 'status' => 'Desactivado'],
            ['codigo' => '94200', 'valor' => 'Actividades de sindicatos', 'status' => 'Desactivado'],
            ['codigo' => '94910', 'valor' => 'Actividades de organizaciones religiosas', 'status' => 'Desactivado'],
            ['codigo' => '94920', 'valor' => 'Actividades de organizaciones políticas', 'status' => 'Desactivado'],
            ['codigo' => '94990', 'valor' => 'Actividades de otras asociaciones n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '95110', 'valor' => 'Reparación de computadoras y equipo periférico', 'status' => 'Desactivado'],
            ['codigo' => '95120', 'valor' => 'Reparación de equipos de comunicación', 'status' => 'Desactivado'],
            ['codigo' => '95210', 'valor' => 'Reparación de aparatos electrónicos de consumo', 'status' => 'Desactivado'],
            ['codigo' => '95220', 'valor' => 'Reparación de aparatos electrodomésticos y de equipo para el hogar y el jardín', 'status' => 'Desactivado'],
            ['codigo' => '95230', 'valor' => 'Reparación de calzado y artículos de cuero', 'status' => 'Desactivado'],
            ['codigo' => '95240', 'valor' => 'Reparación de muebles y accesorios para el hogar', 'status' => 'Desactivado'],
            ['codigo' => '95290', 'valor' => 'Reparación de otros efectos personales y enseres domésticos', 'status' => 'Desactivado'],
            ['codigo' => '96010', 'valor' => 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel', 'status' => 'Desactivado'],
            ['codigo' => '96020', 'valor' => 'Peluquería y otros tratamientos de belleza', 'status' => 'Desactivado'],
            ['codigo' => '96030', 'valor' => 'Pompas fúnebres y actividades conexas', 'status' => 'Desactivado'],
            ['codigo' => '96090', 'valor' => 'Otras actividades de servicios personales n.c.p.', 'status' => 'Desactivado'],
            ['codigo' => '97000', 'valor' => 'Hogares privados con servicio doméstico', 'status' => 'Desactivado'],
            ['codigo' => '99000', 'valor' => 'Actividades de organizaciones y órganos extraterritoriales', 'status' => 'Desactivado']
        ];

        DB::table('actividad_economicas')->insert($actividades);
    }
}
