<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistritosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $distritos = [
            ['codigo' => '01', 'distrito' => 'AHUACHAPAN', 'municipio' => 2, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'APANECA', 'municipio' => 2, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'ATIQUIZAYA', 'municipio' => 1, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'CONCEPCION DE ATACO', 'municipio' => 2, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'EL REFUGIO', 'municipio' => 1, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'GUAYMANGO', 'municipio' => 3, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'JUJUTLA', 'municipio' => 3, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'SAN FRANCISCO MENENDEZ', 'municipio' => 3, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'SAN LORENZO', 'municipio' => 1, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'SAN PEDRO PUXTLA', 'municipio' => 3, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'TACUBA', 'municipio' => 2, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'TURIN', 'municipio' => 1, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'CANDELARIA DE LA FRONTERA', 'municipio' => 37, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'COATEPEQUE', 'municipio' => 36, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'CHALCHUAPA', 'municipio' => 37, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'EL CONGO', 'municipio' => 36, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'EL PORVENIR', 'municipio' => 37, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'MASAHUAT', 'municipio' => 34, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'METAPAN', 'municipio' => 34, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'SAN ANTONIO PAJONAL', 'municipio' => 37, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'SAN SEBASTIAN SALITRILLO', 'municipio' => 35, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'SANTA ANA', 'municipio' => 34, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'SANTA ROSA GUACHIPILIN', 'municipio' => 37, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'SANTIAGO DE LA FRONTERA', 'municipio' => 34, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'TEXISTEPEQUE', 'municipio' => 37, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'ACAJUTLA', 'municipio' => 41, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'ARMENIA', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'CALUCO', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'CUISNAHUAT', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'SANTA ISABELI ISHUATAN', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'IZALCO', 'municipio' => 38, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'JUAYUA', 'municipio' => 38, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'NAHUIZALCO', 'municipio' => 39, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'NAHUILINGO', 'municipio' => 38, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'SALCOATITAN', 'municipio' => 38, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'SAN ANTONIO DEL MONTE', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'SAN JULIAN', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'SANTA CATARINA MASAHUAT', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'SANTO DOMINGO GUZMAN', 'municipio' => 40, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'SONSONATE', 'municipio' => 38, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'SONZACATE', 'municipio' => 39, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'AGUA CALIENTE', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'ARCATAO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'AZACUALPA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'CITALA', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'COMALAPA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'CONCEPCION QUEZALTEPEQUE', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'CHALATENANGO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'DULCE NOMBRE DE MARIA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'EL CARRIZAL', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'EL PARAISO', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'LA LAGUNA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'LA PALMA', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'LA REINA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'LAS VUELTAS', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'NOMBRE DE JESUS', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'NUEVA CONCEPCION', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'NUEVA TRINIDAD', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'OJOS DE AGUA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'POTONICO', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'SAN ANTONIO DE LA CRUZ', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'SAN ANTONIO LOS RANCHOS', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'SAN FERNANDO', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'SAN FRANCISCO LEMPA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'SAN FRANCISCO MORAZAN', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'SAN IGNACIO', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'SAN ISIDRO LABRADOR', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'SAN JOSE CANCASQUE', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'SAN JOSE FLORES', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'SAN LUIS DEL CARMEN', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'SAN MIGEL DE MERCEDES', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'SAN RAFAEL', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'SANTA RITA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '17', 'distrito' => 'TEJUTLA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '18', 'distrito' => 'ANTGO CUSCATLAN', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '19', 'distrito' => 'CIUDAD ARCE', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '20', 'distrito' => 'COLON', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '21', 'distrito' => 'COMASAGUA', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '22', 'distrito' => 'CHILTIUPAN', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '23', 'distrito' => 'HUIZUCAR', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '24', 'distrito' => 'JAYAQUE', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '25', 'distrito' => 'JICALAPA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '26', 'distrito' => 'LA LIBERTAD', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '27', 'distrito' => 'NUEVO CUSCATLAN', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '28', 'distrito' => 'SANTA TECLA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '29', 'distrito' => 'QUEZALTEPEQUE', 'municipio' => 14, 'status' => 'Activo'],
            ['codigo' => '30', 'distrito' => 'SACACOYO', 'municipio' => 12, 'status' => 'Activo'],
            ['codigo' => '31', 'distrito' => 'SAN JOSE VILLANUEVA', 'municipio' => 13, 'status' => 'Activo'],
            ['codigo' => '32', 'distrito' => 'SAN JUAN OPICO', 'municipio' => 16, 'status' => 'Activo'],
            ['codigo' => '33', 'distrito' => 'SAN MATIAS', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '34', 'distrito' => 'SAN PABLO TACACHICO', 'municipio' => 14, 'status' => 'Activo'],
            ['codigo' => '35', 'distrito' => 'TAMANIQUE', 'municipio' => 13, 'status' => 'Activo'],
            ['codigo' => '36', 'distrito' => 'TALNIQUE', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '37', 'distrito' => 'TEOTEPEQUE', 'municipio' => 14, 'status' => 'Activo'],
            ['codigo' => '38', 'distrito' => 'TEPECOYO', 'municipio' => 16, 'status' => 'Activo'],
            ['codigo' => '39', 'distrito' => 'ZARAGOZA', 'municipio' => 11, 'status' => 'Activo'],
            ['codigo' => '40', 'distrito' => 'AGUILARES', 'municipio' => 13, 'status' => 'Activo'],
            ['codigo' => '41', 'distrito' => 'APOPA', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '42', 'distrito' => 'AYUTUXTEPEQUE', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '43', 'distrito' => 'CUSCATANCINGO', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '44', 'distrito' => 'EL PAISNAL', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '45', 'distrito' => 'GUAZAPA', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '46', 'distrito' => 'ILOPANGO', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '47', 'distrito' => 'MEJICANOS', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '48', 'distrito' => 'NEJAPA', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '49', 'distrito' => 'PANCHIMALCO', 'municipio' => 13, 'status' => 'Activo'],
            ['codigo' => '50', 'distrito' => 'ROSARIO DE MORA', 'municipio' => 13, 'status' => 'Activo'],
            ['codigo' => '51', 'distrito' => 'SAN MARCOS', 'municipio' => 14, 'status' => 'Activo'],
            ['codigo' => '52', 'distrito' => 'SAN MARTIN', 'municipio' => 15, 'status' => 'Activo'],
            ['codigo' => '53', 'distrito' => 'SAN SALVADOR', 'municipio' => 16, 'status' => 'Activo'],
            ['codigo' => '54', 'distrito' => 'SANTIAGO TEXACUANGOS', 'municipio' => 14, 'status' => 'Activo'],
            ['codigo' => '55', 'distrito' => 'SANTO TOMAS', 'municipio' => 16, 'status' => 'Activo'],
            ['codigo' => '56', 'distrito' => 'SOYAPANGO', 'municipio' => 16, 'status' => 'Activo'],
            ['codigo' => '57', 'distrito' => 'TONACATEPEQUE', 'municipio' => 16, 'status' => 'Activo'],
            ['codigo' => '58', 'distrito' => 'CIUDAD DELGADO', 'municipio' => 17, 'status' => 'Activo'],
            ['codigo' => '59', 'distrito' => 'CANDELARIA', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '60', 'distrito' => 'COJUTEPEQUE', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '61', 'distrito' => 'EL CARMEN', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '62', 'distrito' => 'EL ROSARIO', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '63', 'distrito' => 'MONTE SAN JUAN', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '64', 'distrito' => 'ORATORIO DE CONCEPCION', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '65', 'distrito' => 'SAN BARTOLOME PERULAPIA', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '66', 'distrito' => 'SAN CRISTOBAL', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '67', 'distrito' => 'SAN JOSE GUAYABAL', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '68', 'distrito' => 'SAN PEDRO PERULAPAN', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '69', 'distrito' => 'SAN RAFAEL CEDROS', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '70', 'distrito' => 'SAN RAMON', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '71', 'distrito' => 'SANTA CRUZ ANALQUITO', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '72', 'distrito' => 'SANTA CRUZ MICHAPA', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '73', 'distrito' => 'SUCHITOTO', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '74', 'distrito' => 'TENANCINGO', 'municipio' => 18, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'CUYULTITAN', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'EL ROSARIO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'JERUSALEN', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'MERCEDES LA CEIBA', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'OLOCUILTA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'PARAISO OSORIO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'SAN ANTONIO MASAHUAT', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'SAN EMIGDIO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'SAN FRANCISCO CHINAMECA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'SAN JUAN NONUALCO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'SAN JUAN TALPA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'SAN JUAN TEPEZONTES', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'SAN LUIS TALPA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'SAN MIGUEL TEPEZONTES', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'SAN PEDRO MASAHUAT', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'SAN PEDRO NONUALCO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '17', 'distrito' => 'SAN RAFAEL OBRAJUELO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '18', 'distrito' => 'SANTA MARIA OSTUMA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '19', 'distrito' => 'SANTIAGO NONUALCO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '20', 'distrito' => 'TAPALHUACA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '21', 'distrito' => 'ZACATECOLUCA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '22', 'distrito' => 'SAN LUIS LA HERRADURA', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'CINQUERA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'GUACOTECTI', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'ILOBASCO', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'JUTIAPA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'SAN ISIDRO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'SENSUNTEPEQUE', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'TEJUTEPEQUE', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'VICTORIA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'DOLORES', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'APASTEPEQUE', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'GUADALUPE', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'SAN CAYETANO ISTEPEQUE', 'municipio' => 6, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'SANTA CLARA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'SANTO DOMINGO', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'SAN ESTEBAN CATARINA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'SAN ILDEFONSO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '17', 'distrito' => 'SAN LORENZO', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '18', 'distrito' => 'SAN SEBASTIAN', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '19', 'distrito' => 'SAN VICENTE', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '20', 'distrito' => 'TECOLUCA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '21', 'distrito' => 'TEPETITAN', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '22', 'distrito' => 'VERAPAZ', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '23', 'distrito' => 'ALEGRIA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '24', 'distrito' => 'BERLIN', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '25', 'distrito' => 'CALIFORNIA', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '26', 'distrito' => 'CONCEPCION BATRES', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '27', 'distrito' => 'EL TRIUNFO', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '28', 'distrito' => 'EREGUAYQUIN', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '29', 'distrito' => 'ESTANZUELAS', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '30', 'distrito' => 'JUQUILISCO', 'municipio' => 8, 'status' => 'Activo'],
            ['codigo' => '31', 'distrito' => 'JUCUAPA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '32', 'distrito' => 'JUCUARAN', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '33', 'distrito' => 'MERCEDES UMAÑA', 'municipio' => 7, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'NUEVA GRANADA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'OZATLAN', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'PUERTO EL TRIUNFO', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'SAN AGUSTIN', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'SAN BUENAVENTURA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'SAN DIONISIO', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'SANTA ELENA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'SAN FRANCISCO JAVIER', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'SANTA MARIA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'SANTIAGO DE MARIA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'TECAPAN', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'USULUTAN', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'CAROLINA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'CIUDAD BARRIOS', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'COMACARAN', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'CHAPELTIQUE', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '17', 'distrito' => 'CHINAMECA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '18', 'distrito' => 'CHIRILAGUA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '19', 'distrito' => 'EL TRANSITO', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '20', 'distrito' => 'LOLOTIQUE', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '21', 'distrito' => 'MONCAGUA', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '22', 'distrito' => 'NUEVA GUADALUPE', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '23', 'distrito' => 'NUEVO EDEN DE SAN JUAN', 'municipio' => 33, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'QUELEPA', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'SAN ANTONIO DEL MOSCO', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'SAN GERARDO', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'SAN JORGE', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'SAN LUIS DE LA REINA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'SAN MIGUEL', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'SAN RAFAEL ORIENTE', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'SESORI', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'ULUAZAPA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'ARAMBALA', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'CACAOPERA', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'CORINTO', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'CHILANGA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'DELICIAS DE CONCEPCION', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'EL DIVISADERO', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'EL ROSARIO', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '17', 'distrito' => 'GUALOCOCTI', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '18', 'distrito' => 'GUATAJIAGUA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '19', 'distrito' => 'JOATECA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '20', 'distrito' => 'JOCOAITIQUE', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '21', 'distrito' => 'JOCORO', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '22', 'distrito' => 'LOLOTIQUILLO', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '23', 'distrito' => 'MEANGUERA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '24', 'distrito' => 'OSICALA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '25', 'distrito' => 'PERQUIN', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '26', 'distrito' => 'SAN CARLOS', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '27', 'distrito' => 'SAN FERNANDO', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '28', 'distrito' => 'SAN FRANCISCO GOTERA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '29', 'distrito' => 'SAN ISIDRO', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '30', 'distrito' => 'SAN SIMON', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '31', 'distrito' => 'SENSEMBRA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '32', 'distrito' => 'SOCIEDAD', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '33', 'distrito' => 'TOROLA', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '01', 'distrito' => 'YAMABAL', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '02', 'distrito' => 'YOLOAIQUIN', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '03', 'distrito' => 'ANAMOROS', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '04', 'distrito' => 'BOLIVAR', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '05', 'distrito' => 'CONCEPCION DE ORIENTE', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '06', 'distrito' => 'CONCHAGUA', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '07', 'distrito' => 'EL CARMEN', 'municipio' => 22, 'status' => 'Activo'],
            ['codigo' => '08', 'distrito' => 'EL SAUCE', 'municipio' => 23, 'status' => 'Activo'],
            ['codigo' => '09', 'distrito' => 'INTIPUCA', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '10', 'distrito' => 'LA UNION', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '11', 'distrito' => 'LISLIQUE', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '12', 'distrito' => 'MEANGUERA DEL GOLFO', 'municipio' => 20, 'status' => 'Activo'],
            ['codigo' => '13', 'distrito' => 'NUEVA ESPARTA', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '14', 'distrito' => 'PASAQUINA', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '15', 'distrito' => 'POLOROS', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '16', 'distrito' => 'SAN ALEJO', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '17', 'distrito' => 'SAN JOSE LAS FUENTES', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '18', 'distrito' => 'SANTA ROSA LIMA', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '19', 'distrito' => 'YAYANTIQUE', 'municipio' => 21, 'status' => 'Activo'],
            ['codigo' => '20', 'distrito' => 'YUCUAIQUIN', 'municipio' => 21, 'status' => 'Activo'],
        ];

        foreach ($distritos as $distrito) {
            DB::table('distritos')->updateOrInsert(
                ['codigo' => $distrito['codigo'], 'municipio' => $distrito['municipio']],
                ['distrito' => $distrito['distrito'], 'status' => $distrito['status']]
            );
        }
    }
}
